version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd backend-partymodel
      - npm install
      - cd ../frontend-partymodel
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
  s3:
    bucket: party-artifacts-1
    path: party-model
